spring:
  application:
    name: springskills
  h2:
    console:
      enabled: true
logging:
  file:
    name: logs/application.log
  level:
    root: ERROR
    fr.descamps.springskills: DEBUG
  console:
    level: DEBUG